# Generated by Django 4.2.4 on 2023-08-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='blog_link',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='image',
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='description',
            field=models.TextField(),
        ),
    ]
