# Generated by Django 4.2.4 on 2023-08-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blogmodel_blog_link_remove_blogmodel_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
